--- 
- name: 
  hosts: haproxy
  tasks:
    - apt: name=haproxy state=present
      
- name: check apache2 ip address, understand the varible
  hosts: web
  tasks:
    - debug: msg="now I am host {{ inventory_hostname }}" 
    - debug: var=hostvars[inventory_hostname]
    - debug: msg=" ip4 address is {{ ansible_eth0.ipv4.address }}"
    - set_fact: "ipv4={{ ansible_eth0.ipv4.address }}"
 
- name: checking variables
  hosts: web
  tasks:
    - debug: var=inventory_hostname
    - debug: msg="{{ hostvars['web1_1']['ansible_eth0']['ipv4']['address'] }}"
    - debug: msg="ipv4 is {{ ipv4 }}"
        
# - name: install extra packages: curl using different variable method
#   vars: 
#      package: curl
#   tasks:
#      
# - name: install extra packages: wget/socat using with_items
#   tasks:
#     - apt: name= {{ item }} state=present
#
# - name: fail if the /etc/haproxy/haproxy.cfg doesn't exist
#   tasks:
#     - stat: path=/etc/haproxy/haproxy.cfg
#        register: status
#      - fail: msg="doesn't exist"
#         when: ??     