--- 
- name: create directory
  hosts: web
  tasks:
    - name: create directory 
      file: path=/ansible state=directory

- name: update apt repo
  hosts: all:!localhost
  tasks:
    - name: update apt repo
      apt:  update-cache=yes
      
- name: install web server
  hosts: web
  tasks:
    - name: install apache2 web server
      apt: name=apache2 state=present

    - name: make the service ready
      service: name=apache2 state=running
  