---
- name:
  hosts: web
  #gather_facts: no
  tasks:
  
- name:
  hosts: haproxy
  tasks:
  - name: Configure the haproxy cnf file with hosts
    template: src=templates/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
    notify: restart haproxy
  
  handlers:
    - name: restart haproxy
      service: name=haproxy state=restarted