--- 
- name: set system proxy for all and update cache in advance
  hosts: all:!localhost
  vars: 
    http_proxy: http://proxy.example.com
  tasks:
    - name: set proxy, use -e http_proxy from command line
      lineinfile: line='Acquire::http::proxy "{{ http_proxy }}";' dest=/etc/apt/apt.conf.d/95proxies  create=yes
